pipeline {
    agent any

    environment {
        PYTHON = 'C:\\Users\\user\\AppData\\Local\\Python\\bin\\python.exe'
        WORKDIR = 'jenkins_project'
        VIRTUAL_ENV = 'venv'
    }

    stages {

        stage('Setup') {
            steps {
                script {
                    bat """
                    cd %WORKDIR%
                    \"%PYTHON%\" -m venv %VIRTUAL_ENV%
                    call %VIRTUAL_ENV%\\Scripts\\activate
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements.txt
                    """
                }
            }
        }

        stage('Lint') {
            steps {
                bat """
                cd %WORKDIR%
                call %VIRTUAL_ENV%\\Scripts\\activate
                python -m flake8 app.py
                """
            }
        }

        stage('Test') {
            steps {
                bat """
                cd %WORKDIR%
                call %VIRTUAL_ENV%\\Scripts\\activate
                python -m pytest
                """
            }
        }

        stage('Deploy') {
            steps {
                bat """
                cd %WORKDIR%
                call %VIRTUAL_ENV%\\Scripts\\activate
                echo Deploying application...
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
